### ISSUE TITLE
Please release v0.5.3

### ISSUE THREAD

**Issue by samrocketman** [doctormo/python-gitlab3#13]
It seems that v0.5.2 of `python-gitlab3` still has a critical bug.

https://github.com/alexvh/python-gitlab3/blob/v0.5.2/gitlab3/__init__.py#L354

However, if you use master the bug is fixed.

https://github.com/alexvh/python-gitlab3/blob/master/gitlab3/__init__.py#L354-L355

I'm getting reports of users having trouble because of this and I didn't realize it before.  Could you please release v0.5.3 based off of master?

My own local issue for tracking is sag47/gitlab-mirrors#27.  I see you have v0.5.3 and v0.5.4 listed in the changelog.  Perhaps this just needs to be tagged.

**Comment by alexvh** [comment]
Tags added. Thanks for report.
