### ISSUE TITLE
NotImplementedError: a tzinfo subclass must implement dst()

### ISSUE THREAD

**Issue by bwrsandman** [doctormo/python-gitlab3#15]
The class GitLabTzInfo doesn't implement [`dst()`](https://docs.python.org/2/library/datetime.html#datetime.datetime.dst)

The result is a NotImplementedError while trying to do `strftime` on a commit date:

``` python
In [109]: create_date = gl.project(1).commits()[0].created_at

In [110]: create_date.strftime("%Y")
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-110-a0314fffbd8e> in <module>()
----> 1 create_date.strftime("%Y")

NotImplementedError: a tzinfo subclass must implement dst()
```

A work-around is to set `create_date.tzinfo.dst = lambda _: None`

https://github.com/alexvh/python-gitlab3/blob/master/gitlab3/__init__.py#L359

**Comment by doctormo** [comment]
Should be fixed now.
