### ISSUE TITLE
Boolean values are incorrectly marshaled on save

### ISSUE THREAD

**Issue by ulope** [doctormo/python-gitlab3#18]
Boolean values (e.g. `Hook.push_events`) are incorrectly handled on `save()`.
A value of `True` is interpreted as false by the Gitlab API. Since in objects loaded from the Gitlab API boolean values are converted to Python types, all boolean fields will be set to false on save.

**Comment by doctormo** [comment]
The API currently handles boolean values correctly. Tests on the project object save() show True and False being saved correctly from python to the API.
