### ISSUE TITLE
Self-Signed Certificates

### ISSUE THREAD

**Issue by devnetf** [doctormo/python-gitlab3#2]
I saw there is a correction on Self-Signed Certificates, but this functionality is not working yet. I still cannot connect to my gitlab due to get request fail. When will the Self-Signed Certificates issue will be release?

**Comment by alexvh** [comment]
I missed those changes on the last pypi upload. Just pushed a new version containing those changes so an upgrade should fix things for you.

**Comment by devnetf** [comment]
Thanks a lot! I have a suggestion though.  I think ssl_verify=None (which does nothing) should be ssl_verify=True for the default value of ssl_verify since it is a boolean. It took me a while to read the code and the request documentation to find out that I need to pass in False to disable the ssl verification.

**Comment by alexvh** [comment]
Good point; that makes things clearer. Made the change to be pushed out later.

**Comment by devnetf** [comment]
Can this module do things like pull a file from the repo and then later commit and push it back? It would be good to have examples like that.

**Comment by alexvh** [comment]
It can grab a file from a repo, but GitLab's API doesn't have support for committing. For that kind of work you'll want to use something like GitPython (https://gitorious.org/git-python).

For grabbing a file with this, you use Project.get_blob(), e.g.:
project = gl.get_project(1)
readme_contents = project.get_blob('master', 'README')

Doc: http://alexvh.github.io/python-gitlab3/gitlab3.GitLab.Project-class.html
