### ISSUE TITLE
API interfaces are out of date

### ISSUE THREAD

**Issue by samrocketman** [doctormo/python-gitlab3#20]
The latest [GitLab API](http://doc.gitlab.com/ce/api/projects.html#create-project) create project documentation includes the optional parameter `namespace_id` which I would like to use.  I have an open enhancement with samrocketman/gitlab-mirrors#66.  Any chance you could get around to updating the API?  If you like we could use this ticket to track which API interfaces are out of date.

**Comment by samrocketman** [comment]
@alexvh are you no longer supporting this library?  If that's the case I'll need to swap your library out for something else.  Please let me know.

**Comment by alexvh** [comment]
I've been intending to do somewhat of a rewrite for awhile, which has been making me reluctant to update it as it stands. Given the lack of progress on that though, I'll see about getting it up to date within the next few weeks.

**Comment by samrocketman** [comment]
Any update on improving the API compatibility with the current version of GitLab?

**Comment by g3kk0** [comment]
+1

**Comment by lyda** [comment]
I'm also interested in this.  The library is missing support for the [services api](http://doc.gitlab.com/ce/api/services.html) and I'm spending way too much time trying to monkey patch it in.

**Comment by logicminds** [comment]
@alexvh has it been a few weeks yet?  Are you still maintaining this?  This is still an issue.

**Comment by logicminds** [comment]
I think the real problem is that gitlab now has an API for creating projects without needed the user. So we just need to add this new api call.  I can attempt to patch this but my python is weak.

```
Create project
Creates a new project owned by the authenticated user.

POST /projects
Parameters:

name (required) - new project name
path (optional) - custom repository name for new project. By default generated based on name
namespace_id (optional) - namespace for the new project (defaults to user)
description (optional) - short project description
issues_enabled (optional)
merge_requests_enabled (optional)
wiki_enabled (optional)
snippets_enabled (optional)
public (optional) - if true same as setting visibility_level = 20
visibility_level (optional)
import_url (optional)
```

**Comment by ssbarnea** [comment]
Damn, disappointed to find out that more than an year after, the ability to create project in a namespace is still missing from the library.

Is anyone using another library? Or should I just rely on curl itself.

**Comment by logicminds** [comment]
Actually, one can create a project in a namespace without any updates to this api.  This api allows the passing of any number of arguments and namespace_id can be one of them.

Example below:

``` python
project_options={
    'issues_enabled': options.issues,
    'wall_enabled': options.wall,
    'merge_requests_enabled': options.merge,
    'wiki_enabled': options.wiki,
    'snippets_enabled': options.snippets,
    'public': options.public,
    'namespace_id': git.find_group(name=gitlab_namespace).id,

  }
  print >> stderr, "Creating new project %s" % pname
  git.add_project(pname,description=description,**project_options)
```

**Comment by doctormo** [comment]
I believe this bug is out of date now since the api supports namespace_id on projects (although there's plenty of other api cruft still there)
