### ISSUE TITLE
get single project by id or namespace/name

### ISSUE THREAD

**Issue by fopina** [doctormo/python-gitlab3#23]
V3 API allows to get a single project by _id_ or _NAMESPACE/PROJECT_NAME_

```
Get single project

Get a specific project, identified by project ID or NAMESPACE/PROJECT_NAME, which is owned by     the authenticated user. If using namespaced projects call make sure that the     NAMESPACE/PROJECT_NAME is URL-encoded, eg. /api/v3/projects/diaspora%2Fdiaspora (where / is     represented by %2F).

GET /projects/:id
Parameters:

id(required) - The ID or NAMESPACE/PROJECT_NAME of a project
```

Using `gitlab3.project('namespace/projectname')` yelds _ResourceNotFound_ as it doesn't encode the '/'

Easily worked around by doing so in the call (`gitlab3.project('namespace%2Fprojectname')`) but maybe it should be done by the library itself.

**Comment by doctormo** [comment]
Fixed now. Thanks for the report.
