### ISSUE TITLE
Use incremental tags

### ISSUE THREAD

**Issue by samrocketman** [doctormo/python-gitlab3#3]
I request that you use incremental tags for your releases.  I'm currently using another library but have an open issue to use yours (see sag47/gitlab-mirrors#11).  e.g.
- 5e03b23c6612e17dbdf86e75a8a8b7acdb3bf60d - tag `v0.2.0`
- 74f55a59ad8a5b9d46d09714dd1f90c8a9cd9109 - tag `v0.2.1`
- dc51069c491cfea9abc612a1ff5a7f21c9d25810 - tag `v0.3.0`
- 0888f2500e83646144346dabcb465efd8c4c5b06 - tag `v0.4.0`
- 62297a827858356f3e21437ccbc2e8daceccf4b4 - tag `v0.4.1`
- c825b73b8968e9c9a977e5560542d9e42d41d715 - tag `v0.4.2`

The [`setup.py` history](https://github.com/alexvh/python-gitlab3/commits/master/setup.py) would be a good place to start for deciding what commits to tag with versions.

This would be highly beneficial to me.  Right now the current library I'm using doesn't use tags the way I would like and the development workflow seems to be unstable (they're still learning workflow so that's expected).  However, if you note in my [prerequisite documentation](https://github.com/sag47/gitlab-mirrors/blob/development/docs/prerequisites.md#required-software) you'll see that I refer to the commit ID of the `pyapi-gitlab` library rather than using a tag or a branch.  This is to ensure guaranteed compatibility when installing my software.  I'm writing my software with the intention to run it on production systems so I'd like a stable library to use.

If you use tags then I will be able to easily refer to a tag rather than a very large commit ID.  Commit IDs don't bode well for someone implementing my software in a production system.  It seems you already have a good set up for tagging but you just haven't done it yet.

**Comment by alexvh** [comment]
Added tags for past releases, and I'll continue to tag new releases. Thanks for the suggestion

**Comment by samrocketman** [comment]
Much appreciated! :dancers:
